### ISSUE TITLE
Standard filter names

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#107]
Image.filter has a filter that will be custom for each instrument, and it should stay that way.

It would be good to create a list of "standard" filters, and then add a "nearest_standard_filter" message or some such to Instrument, so that we could know which filters are the most comparable.

The use case that prompted this: when astrometrically matching to Gaia, there are three Gaia magnitudes to choose from.  The best one to choose would be the ones closest to the filter of the image we're trying to match.  The only way to do this sanely is to have some kind of mapping to a standard filter; obviously we don't want to have a bunch of instrument-specific comparisons in the class that produces or uses gaia catalogs.

**Comment by guynir42** [comment]
One way to do it is to have a concept of a bandwidth/central wavelength or a lambda_low / lambda_high that would be associated with each Instrument's filter (this would be a dictionary with some reasonable defaults in the Instrument class and you'd expand/replace it in each subclass of Instrument). 

Then you can have a simple mathematical tool that gives you the filter with the "most overlap". I think that is well defined as long as you assume tophat filters (for simplicity). 

I think the harder question would be: what happens when none of the filters match (or poorly match) the catalog filters?

**Comment by guynir42** [comment]
Addressed by #116
