### ISSUE TITLE
Fast identification of stars/galaxies/cosmic rays

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#118]
Currently we are relying on SExtractor to tell us which sources are stars and which are galaxies. 
This is really slow and could be a bottleneck. I think this problem is not so hard that it should take minutes on a single CCD. 

Here are a couple of things we can consider down the line to make this faster:
1) what if we don't rely on our code to find stars, but instead just look for things that are close to the catalog's stars. If a source is matched in position (and rough flux estimate) to a star that we know is there, we have a pretty good prior to say it is a star. 
Maybe I'm missing something, but it seems to me a lot easier to identify star/galaxy this way. 

2) we can come up with our own galaxy / star separator and make sure it runs quickly (I don't know what SExtractor is doing that takes so long, which is part of the reason I don't trust it). One way can be just match-filtering with multiple widths and throwing away too-wide stars (and too-narrow as they can be cosmic rays). Another way is to train our own CNN, but we'd probably do that using labels for stars/galaxies that we find by comparing to catalogs (see option 1) in which case we should probably just use option 1.

**Comment by rknop** [comment]
What SExtractor is doing is documented here:
          https://sextractor.readthedocs.io/en/latest/Position.html#class-star-def                                      
          https://sextractor.readthedocs.io/en/latest/Model.html#spread-model-def                                       

For SPREAD_MODEL, it's fitting a couple of different models to every source in the image, which is why it's taking so long.  This is something that is eminently parallelizable.  I know that SExtractor is able to use threads for some things, but it may not be compiled to do so in the package we're installing.  It's worth checking to see if it's easy to enable this.

It is worth noting that SPREAD_MODEL came out of DES, which was another big survey.  It's the result of people who spent a bunch of time trying to figure out good ways to separate galaxies and stars.  Finding something better is not going to be trivial.

However, I think (1) is the better solution for what we have right now, specifically, photometric calibration, and that's what I've put into the latest itereation of the photometric pipeline.
