### ISSUE TITLE
Alignment as part of Subtraction

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#128]
I feel like we should put Alignment as an integral part of subtraction. 

 - If we leave it as separate process we will have to have data products, i.e., warped images, and I don't want that. 
 - The warped images are only used for making the subtractions, and maybe for making cutouts (which means we will still need to save the warped images, or at least make sure the no-warped new image has reliable WCS that lets you pick the exact right spot for the cutouts). 
 - Alignment could conceivably be a part of the subtraction, e.g., you can imagine doing sub-pixel shifts inside a loop or a minimization algorithm that finds the smallest difference between images, _while doing the subtraction at the same time_. 
 
Discuss!

**Comment by guynir42** [comment]
I am coming to terms with having to have alignment as its own process step. 

Since it is essential that cutouts can come back and pick up the warped image, I don't see a way around keeping that extra data. 
If there is an extra data product it makes sense to have another processing step, with its own provenance and so on. 

This will increase the number of images we are keeping track of by 50% (on top of image and sub_image we will also have warped_image).

**Comment by rknop** [comment]
We may be talking about two different things: processes callable independently, and steps in the subtraction.  I've been conflating them, and that may be part of the problem.

I think we *do* need alignment to be a process that is callable independently of subtraction, so that we can do it even if we don't want to do a subtraction.  However, we do *not* need to save the warped images permanently in the database.

If you are defining "steps in the subtraction" as things where we could pick up at a later date, then, no, I wouldn't make alignment an independent step in the subtraction.  However, I would still keep alignment as a separate process that can be called all by itself.

The step that finds candidates and saves cutouts can be passed a warped reference image, and, if it isn't passed one, it can call a process to rebuild it.  This is fast enough that I don't think it's worth the additional storage to keep the warped reference around permanently.  Most of the time when we're running the pipeline, we'll be doing it all at once; so, the warped reference made for the subtraction can be passed directly on to the candidate finding process.  Only in the event that we redo the candidate finding on an existing subtraction will the calculation of the warped reference need to be redone.
